[supervisord]
nodaemon=true
user=root
[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1440x900x24 -ac
autorestart=true
[program:xfce]
command=/usr/bin/su - orbit -c "DISPLAY=:0 dbus-launch --exit-with-session startxfce4"
autorestart=true
[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -shared -nopw -rfbport 5900
autorestart=true
[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 6080 localhost:5900
autorestart=true
